In [11]:
# Загрузить библиотеку
import numpy as np

In [12]:
# Создать матрицу
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [13]:
# транспонировать матрицу
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [14]:
# Транспонировать вектор
np.array([1, 2, 3, 4, 5, 6]).T

array([1, 2, 3, 4, 5, 6])

In [15]:
# Транспонировать вектор-строку
np.array([[1, 2, 3, 4, 5, 6]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])