In [6]:
# Загрузить библиотеку
import numpy as np

In [7]:
# Создать матрицу
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

In [8]:
# Вернуть диагональные элементы
matrix.diagonal()

array([1, 4, 9])

In [9]:
# Вернуть диагональ на одну выше главной диагонали
matrix.diagonal(offset=1)

array([2, 6])

In [10]:
# Вернуть диагональ на одну ниже главной диагонали
matrix.diagonal(offset=-1)

array([2, 8])