In [1]:
# Загрузить библиотеку
import numpy as np

In [2]:
# Создать вектор-строку
vector = np.array([1, 2, 3, 4, 5, 6])

In [6]:
# Создать матрицу
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [7]:
# Выбрать третий элемент вектора
vector[2]

np.int64(3)

In [8]:
# Выбрать вторую строку, второй столбец
matrix[1, 1]

np.int64(5)

In [12]:
# Выбрать все элементы вектора
vector[:]

array([1, 2, 3, 4, 5, 6])

In [13]:
# Выбрать все вплоть до третьего элемента включетельно
vector[:3]

array([1, 2, 3])

In [16]:
# Выбрать все после третьего элемента
vector[3:]

array([4, 5, 6])

In [20]:
# Выбрать последний элемент
vector[-1]

np.int64(6)

In [23]:
# Выбрать первые две строки и все столбцы матрицы
matrix[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
# Выбрать все строки и второй столбец
matrix[:,1:2]

array([[2],
       [5],
       [8]])