In [18]:
# Загрузить библиотеку
import numpy as np

In [19]:
# Создать матрицу 4х3
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

In [20]:
# Реформировать матрицу в матрицу 2х6
matrix.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [21]:
# Размер миссива matrix
matrix.size

12

In [22]:
# Столько, сколько необходимо
matrix.reshape(1, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [23]:
# Вернуть одномерный массив
matrix.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])